config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

scope 'admin' do
  resources :email_configurations do
    get 'test', on: :member
    get 'fetch', on: :member
  end
end

app/models/email_configuration.rb
# EmailConfiguration Test class
class EmailConfiguration < ActiveRecord::Base
  include Redmine::SafeAttributes
  include EmailTests
  include EmailFetches

  unloadable

  belongs_to :project
  belongs_to :tracker

  validates :configuration_type, presence: true

  validates :host, presence: true
  validates :port, presence: true
  validates :unknown_user, presence: true
  validates :ssl, inclusion: { in: [true, false] }
  validates :username, presence: true
  validates :password, presence: true
  validates :folder, presence: true

  validates :project, presence: true
  validates :tracker, presence: true

  validates :delete_unprocessed, inclusion: { in: [true, false] }
  validates :apop, inclusion: { in: [true, false] }
  validates :no_account_notice, inclusion: { in: [true, false] }
  validates :no_permission_check, inclusion: { in: [true, false] }

  validates :folder, presence: true,
                     uniqueness: { scope: [:host, :port, :username], message: l(:msg_unique_key_folder) }

#  attr_accessible :configuration_type,
#                  :host, :port, :ssl,
#                  :username, :password, :folder,
#                  :move_on_failure, :move_on_success, :delete_unprocessed, :apop,
#                  :unknown_user, :no_account_notice, :no_permission_check, :default_group,
#                  :project_id, :tracker_id, :category, :priority,
#                  :allow_override,
#                  :last_fetch_at, :flg_active

  # SCOPES
  scope :active, lambda {
    where(flg_active: true)
  }

  # Static  function to fetch all the emails from active email configurations
  def self.fetch_all_emails
    configurations = EmailConfiguration.active
    result_out = []

    configurations.each do |email_config|
      test_success, _message = email_config.test_and_fetch_emails

      message = "SUCCESS : #{email_config.log_msg}" if test_success
      message = "ERROR : #{email_config.log_msg}" unless test_success

      result_out << message
    end

    result_out
  end

  def log_msg
    msg = "Fetched '#{configuration_type.upcase}' account '#{username}' "\
      "(folder '#{folder}') at '#{host}':'#{port}'"
    msg
  end
end

app/controllers/email_configurations_controller.rb
# Class responsible for handling EmailConfigurationsController model controller.
class EmailConfigurationsController < ApplicationController
  unloadable

  # GET /email_configurations
  # GET /email_configurations.json
  def index
    @email_configurations = EmailConfiguration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @email_configurations }
    end
  end

  # GET /email_configurations/1
  # GET /email_configurations/1.json
  def show
    @email_configuration = EmailConfiguration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @email_configuration }
    end
  end

  # GET /email_configurations/new
  # GET /email_configurations/new.json
  def new
    @email_configuration = EmailConfiguration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_configuration }
    end
  end

  # GET /email_configurations/1/edit
  def edit
    @email_configuration = EmailConfiguration.find(params[:id])
  end

  # POST /email_configurations
  # POST /email_configurations.json
  def create
    @email_configuration = EmailConfiguration.new(email_params) 

    respond_to do |format|
      if @email_configuration.save
        format.html { redirect_to email_configurations_url, notice: l(:mgs_email_configuration_create_success) }
        format.json { head :no_content }
      else
        format.html { render action: 'new' }
        format.json { render json: @email_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_configurations/1
  # PUT /email_configurations/1.json
  def update
    @email_configuration = EmailConfiguration.find(params[:id])

    respond_to do |format|
      if @email_configuration.update_attributes(email_params)
        format.html { redirect_to email_configurations_url, notice: l(:mgs_email_configuration_update_success) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @email_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_configurations/1
  # DELETE /email_configurations/1.json
  def destroy
    @email_configuration = EmailConfiguration.find(params[:id])
    @email_configuration.destroy

    respond_to do |format|
      format.html { redirect_to email_configurations_url, notice: l(:mgs_email_configuration_deleted_success) }
      format.json { head :no_content }
    end
  end

  # GET /email_configurations/1/fetch
  # GET /email_configurations/1/fetch.json
  def fetch
    @email_configuration = EmailConfiguration.find(params[:id])
    success, message = @email_configuration.test_and_fetch_emails

    if success
      respond_to do |format|
        format.html { redirect_to email_configurations_url, notice: message }
        format.json { head :no_content }
      end

    else
      flash[:error] = message
      respond_to do |format|
        format.html { redirect_to email_configurations_url }
        format.json { head :no_content }
      end
    end
  end

  # GET /email_configurations/1/test
  # GET /email_configurations/1/test.json
  def test
    @email_configuration = EmailConfiguration.find(params[:id])
    success, message = @email_configuration.test

    if success
      respond_to do |format|
        format.html { redirect_to email_configurations_url, notice: message }
        format.json { head :no_content }
      end
    else
      flash[:error] = message

      respond_to do |format|
        format.html { redirect_to email_configurations_url }
        format.json { head :no_content }
      end
    end
  end

  private
    def email_params
      params.require(:email_configuration).permit(:configuration_type,
                  :host, :port, :ssl,
                  :username, :password, :folder,
                  :move_on_failure, :move_on_success, :delete_unprocessed, :apop,
                  :unknown_user, :no_account_notice, :no_permission_check, :default_group,
                  :project_id, :tracker_id, :category, :priority,
                  :allow_override,
                  :last_fetch_at, :flg_active)
    end

end

app/helpers/email_configurations_helper.rb
# Module with EmailConfigurations specific helper methods
module EmailConfigurationsHelper
end

app/views/email_configurations/_form.html.erb
<%= labelled_form_for @email_configuration, validate: true, html: { class: 'tabular' } do |f| -%>

    <%= error_messages_for 'email_configuration' %>

    <div class="box tabular settings">
      <fieldset class="box">
        <legend><%= l(:label_redmine_email_configuration) %></legend>
        <p><%= f.select :configuration_type, [['IMAP', 'imap'], ['POP3', 'pop3']],
                        { include_blank: true, label: l(:field_configuration_type), required: true },
                        { id: 'email_configuration_type' } %> </p>

        <p><%= f.select :flg_active, [[l(:choice_true), 'true'], [l(:choice_false), 'false']],
                        { label: l(:field_flg_active), required: true } %> </p>

        <p>
          <%= f.label :last_fetch_at, { label: l(:field_last_fetch_at) } %>
          <%- if @email_configuration.last_fetch_at.nil? %>
              <%= '---' %>
          <%- else %>
              <%= format_object(@email_configuration.last_fetch_at) %>
          <%- end %>
        </p>
      </fieldset>

      <fieldset class="box" id="email_server_attrs">
        <legend><%= l(:label_email_server) %></legend>
        <p><%= f.text_field :host, required: true, size: 127, label: l(:field_host) %> </p>

        <p><%= f.text_field :port, required: true, label: l(:field_port), placeholder: '(e.g. 993)' %> </p>

        <p><%= f.select :ssl, [[l(:choice_true), 'true'], [l(:choice_false), 'false']], { label: l(:field_ssl), required: true } %> </p>

        <p><%= f.text_field :username, required: true, size: 127, label: l(:field_username) %> </p>

        <p><%= f.password_field :password, { label: l(:field_password), required: true, size: 127, value: @email_configuration.password } %> </p>

        <p><%= f.text_field :folder, required: true, size: 127, label: l(:field_folder), placeholder: '(e.g. INBOX)' %> </p>

        <div id="imap_email_only">
          <p><%= f.text_field :move_on_success, size: 127, label: l(:field_move_on_success) %> </p>

          <p><%= f.text_field :move_on_failure, size: 127, label: l(:field_move_on_failure) %> </p>
        </div>

        <div id="pop3_email_only">
          <p><%= f.select :apop, [[l(:choice_true), 'true'], [l(:choice_false), 'false']], { label: l(:field_apop), required: true } %> </p>

          <p><%= f.select :delete_unprocessed, [[l(:choice_true), 'true'], [l(:choice_false), 'false']],
                          { label: l(:field_delete_unprocessed), required: true } %> </p>
        </div>
      </fieldset>

      <fieldset class="box" id="redmine_email_new_sender_actions">
        <legend><%= l(:label_redmine_email_new_sender_actions) %></legend>
        <p><%= f.select :unknown_user, [[l(:choice_accept), 'accept'], [l(:choice_create), 'create'], [l(:choice_ignore), 'ignore']],
                        { label: l(:field_unknown_user), required: true } %> </p>

        <p><%= f.select :no_account_notice, [[l(:choice_true), 'true'], [l(:choice_false), 'false']],
                        { label: l(:field_no_account_notice), required: true } %> </p>

        <p><%= f.select :no_permission_check, [[l(:choice_true), 'true'], [l(:choice_false), 'false']],
                        { label: l(:field_no_permission_check), required: true } %> </p>

        <p><%= f.text_field :default_group, size: 80, label: l(:field_default_group), placeholder: '(e.g. foo,bar)' %> </p>
      </fieldset>

      <fieldset class="box" id="redmine_email_new_issue_attribures">
        <legend><%= l(:label_redmine_email_new_issue_attribures) %></legend>
        <p><%= f.select :tracker_id, Tracker.order(:name).collect { |p| [p.name, p.id] },
                        { include_blank: true, required: true, label: l(:field_tracker) } %> </p>

        <p><%= f.text_field :category, size: 80, label: l(:field_category) %> </p>

        <p><%= f.select :priority, IssuePriority.order(:name), include_blank: true, required: false,
                        label: l(:field_priority), selected: @email_configuration.priority %> </p>

        <p><%= f.text_field :allow_override, size: 80, label: l(:field_allow_override),
                            placeholder: '(e.g. project,tracker,category,priority)' %> </p>

        <br/>
        <%- @projects = Project.order(:name) -%>
        <fieldset class="box required" id="project">
          <p><%= f.label :project, { label: l(:field_project), required: true } %> </p>

          <div id="projects_list">
            <% if @projects.any? %>
                <%= render_project_nested_lists(@projects) do |p|
                  f.radio_button(:project_id, p.id) + ' ' + h(p)
                end %>
            <% else %>
                <p><%= l(:msg_no_projects) %></p>
            <% end %>
          </div>
        </fieldset>

      </fieldset>
    </div>

    <div id="save_cancel_btn">
      <%= submit_tag l(:button_save) %>
      <%= link_to l(:button_back), email_configurations_path %>
    </div>

    <div id="cancel_btn">
      <%= link_to l(:button_back), email_configurations_path %>
    </div>

<% end -%>



<% content_for :header_tags do %>
    <%= javascript_include_tag 'email_configurations.js', plugin: 'redmine_email_fetcher' %>
<% end %>

<script>
    $(function () {
        // To help item selection
        $("#email_configuration_type").change();
    });
</script>

app/views/email_configurations/edit.html.erb
<div class="contextual">
  <%= link_to l(:button_delete),
              {
                      controller: 'email_configurations',
                      action: 'destroy',
                      id: @email_configuration
              },
              data: { confirm: l(:text_are_you_sure) },
              method: :delete,
              class: 'icon icon-del' %>
</div>

<h2><%= l(:title_email_config_edit) %></h2>

<%= render 'form' %>

app/views/email_configurations/index.html.erb
<h2><%= l(:title_email_config_index) %></h2>


<div class="contextual">
  <%= link_to(l(:label_new_email_configurations), { controller: 'email_configurations', action: 'new' }, class: 'icon icon-add') %>
</div>

<div class="template_box">

  <table class="list issues">
    <thead>
    <tr>
      <th><%= l(:header_config_type) %></th>
      <th><%= l(:header_host) %></th>
      <th><%= l(:header_port) %></th>
      <th><%= l(:header_ssl) %></th>

      <th><%= l(:header_username) %></th>
      <th><%= l(:header_folder) %></th>
      <th><%= l(:header_project) %></th>
      <th><%= l(:header_tracker) %></th>

      <th><%= l(:header_flg_active) %></th>
      <th><%= l(:header_last_fetch_at) %></th>
      <th></th>
    </tr>
    </thead>

    <% @email_configurations.each do |config| %>
        <tr id="email-config-<%= config.id %>">
          <td align="center"><%= config.configuration_type.upcase %></td>
          <td align="center"><%= config.host %></td>
          <td align="center"><%= config.port %></td>
          <td align="center"><%= checked_image config.ssl? %></td>

          <td align="center"><%= config.username %></td>
          <td align="center"><%= config.folder %></td>
          <td align="center"><%= config.project %></td>
          <td align="center"><%= config.tracker %></td>

          <td align="center"><%= checked_image config.flg_active? %></td>
          <td align="center"><%= format_object(config.last_fetch_at) %></td>

          <td class="buttons">
            <%= link_to l(:button_edit), edit_email_configuration_path(config), class: 'icon icon-edit' %>
            <%= link_to l(:button_test), test_email_configuration_path(config), class: 'icon icon-test' %>
            <%= link_to l(:button_fetch), fetch_email_configuration_path(config), class: 'icon icon-test' %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/email_configurations/new.html.erb
<h2><%= l(:title_email_config_new) %></h2>

<%= render 'form' %>